import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

export async function generateStaticParams() {
  return [{ lang: 'id-ID' }, { lang: 'id' }];
}

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

type RootLayoutProps = {
  children: React.ReactNode;
  params: { lang: string };
};

export default function RootLayout({
  children,
  params
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={params.lang}>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
